// <auto-generated />
using System;
using ForumSystemTeamFour.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumSystemTeamFour.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230614120230_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumSystemTeamFour.Models.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dislikes")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ThreadId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("ForumSystemTeamFour.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ufo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Skinwalker"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bigfoot"
                        });
                });

            modelBuilder.Entity("ForumSystemTeamFour.Models.Thread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasMaxLength(8192)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dislikes")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("ForumSystemTeamFour.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Blocked = false,
                            Email = "FirstnameOne@Lastname.com",
                            FirstName = "FirstNameOne",
                            IsAdmin = true,
                            LastName = "LastNameOne",
                            Password = "passwordOne",
                            Username = "UsernameOne"
                        },
                        new
                        {
                            Id = 2,
                            Blocked = false,
                            Email = "FirstnameTwo@Lastname.com",
                            FirstName = "FirstNameTwo",
                            IsAdmin = false,
                            LastName = "LastNameTwo",
                            Password = "passwordTwo",
                            Username = "UsernameTwo"
                        },
                        new
                        {
                            Id = 3,
                            Blocked = false,
                            Email = "FirstnameThree@Lastname.com",
                            FirstName = "FirstNameThree",
                            IsAdmin = false,
                            LastName = "LastNameThree",
                            Password = "passwordThree",
                            Username = "UsernameThree"
                        },
                        new
                        {
                            Id = 4,
                            Blocked = false,
                            Email = "FirstnameFour@Lastname.com",
                            FirstName = "FirstNameFour",
                            IsAdmin = false,
                            LastName = "LastNameFour",
                            Password = "passwordFour",
                            Username = "UsernameFour"
                        },
                        new
                        {
                            Id = 5,
                            Blocked = false,
                            Email = "FirstnameFive@Lastname.com",
                            FirstName = "FirstNameFive",
                            IsAdmin = false,
                            LastName = "LastNameFive",
                            Password = "passwordFive",
                            Username = "UsernameFive"
                        });
                });

            modelBuilder.Entity("TagThread", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.Property<int>("ThreadsId")
                        .HasColumnType("int");

                    b.HasKey("TagsId", "ThreadsId");

                    b.HasIndex("ThreadsId");

                    b.ToTable("TagThread");
                });

            modelBuilder.Entity("ForumSystemTeamFour.Models.Reply", b =>
                {
                    b.HasOne("ForumSystemTeamFour.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("ForumSystemTeamFour.Models.Thread", null)
                        .WithMany("Replies")
                        .HasForeignKey("ThreadId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ForumSystemTeamFour.Models.Thread", b =>
                {
                    b.HasOne("ForumSystemTeamFour.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TagThread", b =>
                {
                    b.HasOne("ForumSystemTeamFour.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForumSystemTeamFour.Models.Thread", null)
                        .WithMany()
                        .HasForeignKey("ThreadsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForumSystemTeamFour.Models.Thread", b =>
                {
                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
